apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: employee-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - employee-app

  selector:
    matchLabels:
      app: employee-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
